### ISSUE TITLE
Project Setup

### ISSUE THREAD

**Issue by raheebwa** [raheebwa/irla-facebook#1]
# Tasks

- [x] Use Postgresql for your database from the beginning
- [x] Enable Bycrypt 
- [x] Enable & init TDD (Rspec, Shoulda matchers, faker, capybara, factorybot)
- [x] Enable CI for linting & tests using stickerci

# Outcome

- [x] Postgres database working in both our PCs
- [X] ~`password_digest` and `#authenticate` method works~ This will be done with Devise later
- [x] `rpec` command works
- [x] `rubocop` working on both PCs
- [x] `stickler` working for the repo

# Resources

Build the new postgresql rails app $ rails new odin-facebook --database=postgresql, initialize the Git repo, and update the README to link back to this page.
