### ISSUE TITLE
User and Post Views must work as required

### ISSUE THREAD

**Issue by Israel-Laguan** [raheebwa/irla-facebook#10]
# Tasks

- [x] Check if interface for creating user works well for set avatar
- [x] Ensure avatar of user is correctly displayed
- [x] Check if showing posts uses the image link correctly
- [x] Modify Post index to show latest posts (don't mind friend posts yet)
- [x] Modify User show to have profile info and posts from the user

# Outcome

- [x] Try some tests for the views
- [x] Inspect visually for inconsistences

# Resources

Posts should always display with the post content, author, comments and likes. 
Treat the Posts Index page like the real Facebook’s “Timeline” feature – show all the recent posts from the current user and users she is friends with.
Users can create a Profile with a Photo (just start by using the Gravatar image like you did in the Rails Tutorial).
The User Show page contains their Profile information, photo, and Posts.
