### ISSUE TITLE
Design Entity Relationship Diagram (ERD) for project

### ISSUE THREAD

**Issue by Israel-Laguan** [raheebwa/irla-facebook#2]
# Tasks

- [x] Create your own ERD. You can use an [online tool](https://www.lucidchart.com/pages/how-to-draw-ERD) to do that or draw it on the piece of paper and take a photo of it.
- [x] Think about friendship and friendship requests. Small hint: try to use status of the friendship to tell if it is a request or confirmed friendship. (Extra hint: keep profile image as a link to gravatar as storing files is a bit tricky in Heroku.)
- [x] Put a file with your ERD in the docs directory in your repo.

# Outcome

- [x] An image with the ERD.

# Resources

- Watch [this video](https://www.youtube.com/watch?v=QpdhBUYk7Kk&vl=en)  about Entity Relationship Diagram (ERD)
- Watch [this video](https://www.youtube.com/watch?v=-CuY5ADwn24) about Primary and Foreign Keys.

Think through the data architecture required to make this work. There are a lot of models and a lot of associations, so take the time to plan out your approach.

**Comment by Israel-Laguan** [comment]
# Sugestion

It says "Use gravatar", but I like [robohash](https://robohash.org/) as an option
