### ISSUE TITLE
Create User Model

### ISSUE THREAD

**Issue by Israel-Laguan** [raheebwa/irla-facebook#3]
# Tasks

- [x] Check for types of columns
- [x] ~Decide if creating model using generator or scaffold~ Devise ask you to install first devise before generating model. Check issue #6 
- [x] Add validations
- [x] make tests

# Outcome

- [x] Test if all columns are available
- [x] Test types on columns
- [x] Test validations

# References

- Issue #2 to check the ERD
- [Project](https://github.com/Israel-Laguan/micro-reddit)

Use the Active Storage to allow users to upload a photo to their profile.
