### ISSUE TITLE
Create Post Model

### ISSUE THREAD

**Issue by Israel-Laguan** [raheebwa/irla-facebook#4]
# Tasks

- [x] Check for types of columns
- [x] Decide if creating model using generator or scaffold
- [x] Add validations
- [x] make tests

# Outcome

- [ ] Test if all columns are available
- [ ] Test types on columns
- [ ] Test validations

# References

- Issue #2 to check the ERD
- [Project](https://github.com/Israel-Laguan/Private-Events)

Make posts also allow images (either just via a URL or, more complicated, by uploading one).
