### ISSUE TITLE
Add associations between Users & Posts

### ISSUE THREAD

**Issue by Israel-Laguan** [raheebwa/irla-facebook#5]
# Tasks

- [x] Check if associations are correct
- [ ] Add association's code in UserController and PostController
- [x] Add association's code in Models and generate Migration if needed
- [x] Apply migrations on db
- [x] make tests

# Outcome

- [x] Test if associations works
- [x] Check `rubocop` in updated files

# References

Users can create Posts (text only to start).

- Issue #2 to check the ERD
- [Project](https://github.com/Israel-Laguan/Private-Events)
