### ISSUE TITLE
Add Auth system using Devise gem

### ISSUE THREAD

**Issue by Israel-Laguan** [raheebwa/irla-facebook#6]
# Tasks

- [ ] Investigate on `Devise` requirements
- [ ] Add to `Gemfile` and bundle
- [ ] Follow `Devise` docs and tutorials until auth system is working
- [ ] make tests

# Outcome

- [ ] Test if user is authenticated
- [ ] Test negative cases like user not providing correct data
- [ ] Try to reproduce on a different PCs

# References

- Devise [documentation](https://github.com/plataformatec/devise)
- Some [articles](https://medium.com/swlh/https-medium-com-melee-santiago-using-devise-gem-to-handle-authentication-in-rails-app-538bbd231dde) or tutorials

User sign-in should use the Devise gem. Devise gives you all sorts of helpful methods so you no longer have to write your own user passwords, sessions, and #current_user methods. See the [Railscast](http://railscasts.com/episodes/209-introducing-devise?view=asciicast) (which uses Rails 3) for a step-by-step introduction. The docs will be fully current.
