### ISSUE TITLE
Users must sign in to see anything except the sign in page.

### ISSUE THREAD

**Issue by Israel-Laguan** [raheebwa/irla-facebook#7]
# Task

- [ ] Check where is needed to redirect if user not signed in
- [ ] Decide if redirection must be automatic of as a button (like facebook does)
- [ ] Implement code on Controllers and views
- [ ] Add tests if possible

# Outcome

- [ ] If user try to enter any page not authorized, must be rejected in some way
- [ ] Tests that fails to show certain views if not signin
- [ ] Tests that sign in correctly
- [ ] Verify if validations from user model needs improvements
