### ISSUE TITLE
Create Comment Model

### ISSUE THREAD

**Issue by Israel-Laguan** [raheebwa/irla-facebook#8]
# Tasks

- [ ] Check for types of columns
- [ ] Add validations
- [ ] make tests

# Outcome

- [ ] Test if all columns are available
- [ ] Test types on columns
- [ ] Test validations

# References

- Issue #2 to check the ERD
