### ISSUE TITLE
Add Omnicast for signin

### ISSUE THREAD

**Issue by Israel-Laguan** [raheebwa/irla-facebook#9]
# Tasks

- [ ] Investigate on `Omniauth` requirements
- [x] Add to `Gemfile` and bundle
- [ ] Follow `Omniauth` docs and tutorials until sign in with Facebook is working
- [ ] Be sure it integrates with `devise`
- [ ] make tests

# Outcome

- [ ] Test if user is authenticated using facebook
- [ ] Test negative cases like user not providing correct data
- [ ] Try to reproduce on a different PCs

# Resources

Sign in should use [Omniauth](https://github.com/plataformatec/devise/wiki/OmniAuth:-Overview) to allow a user to sign in with their real Facebook account. See the [RailsCast](http://railscasts.com/episodes/360-facebook-authentication?view=asciicast) on FB authentication with Devise for a step-by-step look at how it works.

- [Documentation](https://github.com/plataformatec/devise/wiki/OmniAuth:-Overview)
